### ISSUE TITLE
When I copy the code and try to upload it to my esp8266 it gives me this error any ideas?

### ISSUE THREAD

**Issue by CaptiveCreeper** [danielsen2009/homebridge-mqtt-acessories#1]
I coped the code for the fan accessory and it gave me this error. Anybody have any ideas on how to fix it?

Arduino: 1.6.13 (Mac OS X), Board: "NodeMCU 1.0 (ESP-12E Module), 80 MHz, 921600, 4M (3M SPIFFS)"

TestFanWithOTA:42: error: no matching function for call to 'PubSubClient::PubSubClient(IPAddress&, WiFiClient&)'
 PubSubClient client( server,wclient);
                                    ^
PubSubClient::PubSubClient(const char*, uint16_t, std::function<void(char*, unsigned char*, unsigned int)>, Client&, Stream&)
    PubSubClient(const char*, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);
    ^
PubSubClient.h:116:4: note:   candidate expects 5 arguments, 2 provided
PubSubClient.h:115:4: note: PubSubClient::PubSubClient(const char*, uint16_t, std::function<void(char*, unsigned char*, unsigned int)>, Client&)
    PubSubClient(const char*, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);
    ^
PubSubClient.h:115:4: note:   candidate expects 4 arguments, 2 provided
PubSubClient.h:114:4: note: PubSubClient::PubSubClient(const char*, uint16_t, Client&, Stream&)
    PubSubClient(const char*, uint16_t, Client& client, Stream&);
    ^
PubSubClient.h:114:4: note:   candidate expects 4 arguments, 2 provided
PubSubClient.h:113:4: note: PubSubClient::PubSubClient(const char*, uint16_t, Client&)
    PubSubClient(const char*, uint16_t, Client& client);
    ^
PubSubClient.h:113:4: note:   candidate expects 3 arguments, 2 provided
PubSubClient.h:112:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, std::function<void(char*, unsigned char*, unsigned int)>, Client&, Stream&)
    PubSubClient(uint8_t *, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);
    ^
PubSubClient.h:112:4: note:   candidate expects 5 arguments, 2 provided
PubSubClient.h:111:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, std::function<void(char*, unsigned char*, unsigned int)>, Client&)
    PubSubClient(uint8_t *, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);
    ^
PubSubClient.h:111:4: note:   candidate expects 4 arguments, 2 provided
PubSubClient.h:110:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, Client&, Stream&)
    PubSubClient(uint8_t *, uint16_t, Client& client, Stream&);
    ^
PubSubClient.h:110:4: note:   candidate expects 4 arguments, 2 provided
PubSubClient.h:109:4: note: PubSubClient::PubSubClient(uint8_t*, uint16_t, Client&)
    PubSubClient(uint8_t *, uint16_t, Client& client);
    ^
PubSubClient.h:109:4: note:   candidate expects 3 arguments, 2 provided
PubSubClient.h:108:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, std::function<void(char*, unsigned char*, unsigned int)>, Client&, Stream&)
    PubSubClient(IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client, Stream&);
    ^
PubSubClient.h:108:4: note:   candidate expects 5 arguments, 2 provided
PubSubClient.h:107:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, std::function<void(char*, unsigned char*, unsigned int)>, Client&)
    PubSubClient(IPAddress, uint16_t, MQTT_CALLBACK_SIGNATURE,Client& client);
    ^
PubSubClient.h:107:4: note:   candidate expects 4 arguments, 2 provided
PubSubClient.h:106:4: note: PubSubClient::PubSubClient(IPAddress, uint16_t, Client&, Stream&)
    PubSubClient(IPAddress, uint16_t, Client& client, Stream&);
    ^
--------------------------Cut out a whole bunch of other errors to shorten it-------------------------
TestFanWithOTA:163: error: expected unqualified-id before '&' token
 void callback(const MQTT::Publish& pub){
                                  ^
TestFanWithOTA:163: error: expected ')' before '&' token
TestFanWithOTA:163: error: expected initializer before 'pub'
 void callback(const MQTT::Publish& pub){
                                    ^
exit status 1
no matching function for call to 'PubSubClient::PubSubClient(IPAddress&, WiFiClient&)'

**Comment by CaptiveCreeper** [comment]
Ok I figured it out I was using the wrong PubSubClient library. The one the arduino installs is not the right one

**Comment by ghost** [comment]
Can you guide me if you have completed it.
